export const userData = [
    {
        name: 'Jan',
        'Active User': 4000,
        pv: 2400,
        amt: 2400,
    },
    {
        name: 'Feb',
        'Active User': 3000,
        pv: 1398,
        amt: 2210,
    },
    {
        name: 'Mar',
        'Active User': 2000,
        pv: 9800,
        amt: 2290,
    },
    {
        name: 'Apr',
        'Active User': 2780,
        pv: 3908,
        amt: 2000,
    },
    {
        name: 'May',
        'Active User': 1890,
        pv: 4800,
        amt: 2181,
    },
    {
        name: 'Jun',
        'Active User': 2390,
        pv: 3800,
        amt: 2500,
    },
    {
        name: 'Jul',
        'Active User': 3490,
        pv: 4300,
        amt: 2100,
    },
    {
        name: 'Aug',
        'Active User': 1782,
        pv: 4300,
        amt: 2100,
    },
    {
        name: 'Sep',
        'Active User': 1090,
        pv: 4300,
        amt: 2100,
    },
    {
        name: 'Oct',
        'Active User': 2390,
        pv: 4300,
        amt: 2100,
    },
    {
        name: 'Nov',
        'Active User': 3067,
        pv: 4300,
        amt: 2100,
    },
    {
        name: 'Dec',
        'Active User': 2618,
        pv: 4300,
        amt: 2100,
    },
];

export const productData = [
    {
        name: 'Jan',
        'Sales': 4000,
    },
    {
        name: 'Feb',
        'Sales': 3000,
    },
    {
        name: 'Mar',
        'Sales': 2000,
    },
];

export const userRows = [
    { 
        id: 1,
        username: 'Snow',
        avatar: 'img/person.jpg',
        email: 'snow@gmail.com',
        status: 'active',
        transaction: '$546.00'
    },
    { 
        id: 2,
        username: 'Keane',
        avatar: 'img/person.jpg',
        email: 'keane@gmail.com',
        status: 'active',
        transaction: '$232.00',
    },
    { 
        id: 3, 
        username: 'Roy', 
        avatar: 'img/person.jpg',
        email: 'roy@gmail.com',
        status: 'active',
        transaction: '$190.00',
    },
    { 
        id: 4, 
        username: 'Lizzy', 
        avatar: 'img/person.jpg',
        email: 'lizzy@gmail.com',
        status: 'active',
        transaction: '$683.00',
    },
    { 
        id: 5, 
        username: 'Adams', 
        avatar: 'img/person.jpg',
        email: 'adams@gmail.com',
        status: 'active',
        transaction: '$899.00',
    },
    { 
        id: 6, 
        username: 'Rolex', 
        avatar: 'img/person.jpg',
        email: 'rolex@gmail.com',
        status: 'active',
        transaction: '$638.00',
    },
];

export const productRows = [
    {
        id: 1,
        name: "Apple Airpods",
        img: 'img/product/product1.jpg',
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 2,
        name: "Apple Airpods",
        img: 'img/product/product2.jpg',
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
        id: 3,
        name: "Apple Airpods",
        img: 'img/product/product3.jpg',
        stock: 123,
        status: "active",
        price: "$120.00",
    },
    {
      id: 4,
      name: "Apple Airpods",
      img:'img/product/product4.jpg',
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 5,
      name: "Apple Airpods",
      img:'img/product/product5.jpg',
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 6,
      name: "Apple Airpods",
      img:'img/product/product6.jpg',
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 7,
      name: "Apple Airpods",
      img: 'img/product/product7.jpg',
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 8,
      name: "Apple Airpods",
      img: 'img/product/product8.jpg',
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 9,
      name: "Apple Airpods",
      img: 'img/product/product9.jpg',
      stock: 123,
      status: "active",
      price: "$120.00",
    },
    {
      id: 10,
      name: "Apple Airpods",
      img: 'img/product/product10.jpg',
      stock: 123,
      status: "active",
      price: "$120.00",
    },
];